# Generated by Django 4.0.3 on 2022-05-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_societe_creation_societe_modification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='budget_temps_anuel',
            new_name='budget_temps_annuel',
        ),
    ]
