# Generated by Django 4.0.3 on 2022-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_ajoute_par_commentairetimesheet_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipe', to='app.userprofile'),
        ),
    ]
