# Generated by Django 4.0.3 on 2022-05-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_projet_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='equipe',
            field=models.ManyToManyField(blank=True, related_name='equipe', to='app.userprofile'),
        ),
    ]
