# Generated by Django 3.2.4 on 2022-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_projet_description_alter_tache_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='motif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
