# Generated by Django 3.2.4 on 2022-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_demandeconge_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
