# Generated by Django 3.2.4 on 2022-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220528_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=200, null=True),
        ),
    ]
