# Generated by Django 3.2.4 on 2022-10-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_demandeconge_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairetimesheet',
            name='enregistrement',
        ),
        migrations.RemoveField(
            model_name='commentairetimesheet',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='demandeconge',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='ajoute_par',
        ),
        migrations.RemoveField(
            model_name='enregistrementtimesheet',
            name='tache',
        ),
        migrations.RemoveField(
            model_name='enregistrementtimesheet',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='ajoute_par',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='ajoute_par',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='projet',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nom',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='societe',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='CommentaireTimesheet',
        ),
        migrations.DeleteModel(
            name='DemandeConge',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='EnregistrementTimesheet',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.DeleteModel(
            name='Societe',
        ),
        migrations.DeleteModel(
            name='Tache',
        ),
    ]
