# Generated by Django 4.1.4 on 2022-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer_customernotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='identity_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'F')], default='M', max_length=50),
            preserve_default=False,
        ),
    ]
