# Generated by Django 4.1.4 on 2022-12-22 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customer_passport_number_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='complete_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
