# Generated by Django 4.1.4 on 2022-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_complete_name_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identity_type',
            field=models.CharField(choices=[('PASSPORT', 'PASSPORT'), ('ID', 'ID')], default='ID', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=300),
        ),
    ]
