# Generated by Django 4.1.4 on 2022-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customer_identity_type_alter_customer_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
