# Generated by Django 4.1.4 on 2023-01-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_transactionnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='montant',
            new_name='amount',
        ),
    ]
