# Declaring Global Variables

THRESHOLD_ACTOR_CATEGORY = 0.05
DATE_FORMAT = "%Y-%m-%d"
OTHER_SECOND_PER_FIRST_THRESHOLD = 7
MIN_CATEGORIES_SECOND_PER_FIRST_THRESHOLD = 3
MIN_MONTHLY_PLOT_THRESHOLD = 6
MIN_DISTINCT_VALUES_MONTHLY_PLOT_THRESHOLD = 10